# Generated by Django 4.0.1 on 2022-01-19 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('buyer', models.ManyToManyField(related_name='bids_from_user', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ManyToManyField(related_name='bids_from_listing', to='auctions.Listings')),
            ],
        ),
    ]
