# Generated by Django 4.0.1 on 2022-01-19 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='buyer',
        ),
        migrations.AddField(
            model_name='bids',
            name='buyer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bids_from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='bids',
            name='listing',
        ),
        migrations.AddField(
            model_name='bids',
            name='listing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bids_from_listing', to='auctions.listings'),
        ),
    ]
