# Generated by Django 4.0.1 on 2022-04-04 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlists',
            old_name='listing_url',
            new_name='product_url',
        ),
        migrations.RemoveField(
            model_name='watchlists',
            name='listing',
        ),
        migrations.AddField(
            model_name='watchlists',
            name='product_id',
            field=models.ManyToManyField(blank=True, default=0, related_name='ID_from_product', to='auctions.Listings'),
        ),
        migrations.RemoveField(
            model_name='watchlists',
            name='user',
        ),
        migrations.AddField(
            model_name='watchlists',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_from_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
