# Generated by Django 4.0.1 on 2022-04-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_listing_url_watchlists_product_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='is_auction_winner',
            field=models.BooleanField(default=False),
        ),
    ]
