# Generated by Django 4.0.1 on 2022-04-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_bids_is_auction_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, default='None', max_length=64),
        ),
        migrations.AlterField(
            model_name='listings',
            name='picture_url',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
