# Generated by Django 4.0.1 on 2022-05-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_listings_category_alter_listings_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='listings',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
