# Generated by Django 4.0.1 on 2022-05-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listings_current_price_alter_listings_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listings',
            options={'verbose_name_plural': 'Listings'},
        ),
    ]
